---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *" # каждую минуту запускаем джобу
  concurrencyPolicy: Allow # можно запустить джобу, если старая еще не выполнилась
  jobTemplate:
    spec:
      backoffLimit: 2 #сколько раз Kubernetes будет повторно пытаться запустить job, если она завершится с ошибкой
      activeDeadlineSeconds: 100 # если за 100 сек не выполнилась джоба, бы ее убиваем
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: Never # никогда не перезапускам, если завершился с ошибкой
